### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by eroriset** [DetErDugget/dugget_tpset#2]
if you could and would have time, would you try to add: when you teleport (to spawnpoint) your vehicle repair automatically with teleport, This can help you :		
		                                        SetVehicleEngineHealth(vehicle, 1000)
		                                        SetVehicleDirtLevel(vehicle, 0)
		                                        SetVehicleEngineOn( vehicle, true, true )
		                                        SetVehicleFixed(vehicle)

**Comment by DetErDugget** [comment]
It is added
